[package]
name = "mkostenko-core-rust"
version = "0.1.0"
authors = ["mykyta-kostenko-amc <mykyta.kostenko@seequent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib"]

[dependencies]
